POST  http://localhost:3000/devices/ HTTP/1.1
content-type: application/json

{
    "cid": "abcdef",
    "name": "temp sensor 12",
    "source": "Home-Hub",
    "type":"device-type",
    "state": "online",
    "last-seen": "12 mar 2024 ",
    "properties": [
      {
        "ha": "calue of ha",
        "cloud": "value"
      }
    ]
}